language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
  - WARN_AS_ERROR=1
  - MAKEFLAGS="-s"
  - REALM_SYNTHETIC_CORE_MAP=""
  matrix:
  - CC_FLAGS="-std=c++98" DEBUG=0
  - CC_FLAGS="-std=c++98 -DPRIVILEGE_CHECKS -DBOUNDS_CHECKS" DEBUG=1
  - CC_FLAGS="-std=c++98 -DLEGION_SPY" DEBUG=1 USE_SPY=1
  - CC_FLAGS="-std=c++0x" DEBUG=0
  # - CC_FLAGS="-std=c++98" DEBUG=1 USE_GASNET=1 USE_LLVM=1 DISABLE_INNER=1
matrix:
  exclude:
    - os: osx
      compiler: gcc
# blacklist some branches
branches:
  only:
    - configfiletest
before_install:
  - export THREADS=2
  - |
    if [[ "$(uname)" = "Linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo add-apt-repository ppa:pypy/ppa -y
      sudo apt-get update -qq
      sudo apt-get install -qq g++-4.9 clang-3.5 libclang-3.5-dev llvm-3.5-dev openmpi-bin libopenmpi-dev libblas-dev liblapack-dev pypy
    fi
  - |
    if [[ "$(uname)" = "Darwin" ]]; then
      brew update
      brew install pypy homebrew/versions/llvm35
    fi
  - if [[ "$(uname)" = "Linux" && "$CXX" = "g++" ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [[ "$(uname)" = "Linux" && "$CXX" = "clang++" ]]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - if [[ "$(uname)" = "Linux" ]]; then export LLVM_CONFIG="llvm-config-3.5"; fi
  - |
    if [[ "$USE_GASNET" -eq 1 ]]; then
      export CONDUIT=mpi
      export GASNET_ROOT="$PWD/gasnet/release"
      export LAUNCHER="mpirun -n 2 -bind-to none -x TERRA_PATH -x INCLUDE_PATH -x LD_LIBRARY_PATH -x LG_RT_DIR"
      unset WARN_AS_ERROR
      git clone https://github.com/StanfordLegion/gasnet.git gasnet
      pushd gasnet
      make -j$THREADS
      popd
    fi
script:
  - ./test.py -j2
